services:
  db:
    image: postgres:16-alpine
    container_name: token_ledger_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: token_ledger_dev
    secrets:
      - postgres_password
    ports:
      - "5432:5432"
    volumes:
      - token_ledger_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

volumes:
  token_ledger_pgdata:
